cache:
  paths:
  - vendor/

test:
  tags: [grifart/php7.1-with-gulp-and-all-php-modules]
  image: grifart/php7.1-with-gulp-and-all-php-modules
  before_script:
    - composer install --no-interaction --prefer-dist
  script:
    - composer run nette-tester
    - composer run phpstan
