language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - 8.0

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 7.1
          env: COMPOSER_DEPENDENCIES="--prefer-lowest --prefer-stable"

before_script:
    - composer self-update --no-interaction
    - composer update --no-interaction --prefer-dist $COMPOSER_DEPENDENCIES

script:
    - vendor/bin/tester ./tests/cases
    - vendor/bin/phpstan analyse --no-progress --level 7 src/


after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
